### ISSUE TITLE
Vbulletin BBCODE to Markdown converter did not convert

### ISSUE THREAD

**Issue by limitmaker** [akhoury/nodebb-plugin-import#103] opened 2015-01-06 06:20 UTC
am I supposed to have the markdown plugin active when doing this conversion?

**Comment by akhoury** [comment] 2015-01-06 14:53
it shouldnt matter. But you need the markdown plugin active after the conversion is done to see the results. 

Did you see any errors? interesting logs?

**Comment by akhoury** [comment] 2015-01-07 02:23
can you paste the text above as text within a markdown code block
```
[size="3"]Something like this[/size]
```
I want to run some tests against it using the [converter module](https://github.com/akhoury/bbcode-to-markdown)

**Comment by limitmaker** [comment] 2015-01-07 02:42
```
[As always, if anyone, especially ENFPs, has any suggestions for changes or improvements, feel free to comment.]

[SIZE="5"]ENFP: A Jungian Cognitive Function Analysis[/SIZE]
[SIZE="3"]by simulatedworld[/SIZE]
[URL="www.personalitynation.com"]www.personalitynation.com[/URL]

[B]ENFP[/B], or [I]Extroverted iNtuitive Feeling Perceiver[/I], is a label borrowed from MBTI nomenclature and now applied to the Jungian Cognitive Function set [B]{Ne, Fi, Te, Si}[/B].

[B]Dominant: Extroverted iNtuition (Ne)[/B]

[I]"More than anything I need to feel like I'm working toward some kind of meaningful change or improvement in people's lives. I have a lot of big ideas for making things better, and I get really excited about new ideas that point toward some kind of new direction or idea I hadn't thought of before. I usually try to have a lot of people I like around, both because I like having them to bounce my ideas off of, and because it's really important to me to be able to connect with people on a personal level. Sometimes I feel I'm bursting with so many different ideas at once that I have trouble even remembering them all--I can get lost in my imagination. I tend to get involved in so many different interests that I have trouble focusing my attention on just one, and I often end up committing to more things than I really have the time or energy to complete. It's just really important that I be able to change direction and try something different when I hit a dead end and whatever I'm doing stops feeling interesting. I have to get excited about exploring the possibilities of something new before I can really work in my element and show off the full extent of my talents. I need to be doing something creative where I can put my own personal spin on whatever it is that I'm working on. Really, I just work best in a relaxed and open environment where I can have freedom to explore and find what feels right to me, and be appreciated and respected for my talents. What's the point of living life if you aren't pursuing something you're passionate about?"[/I]

Generally regarded as excited, enthusiastic people (albeit someone unfocused and more than a little bit idealistic), ENFPs are explorers who feel most alive when they can connect people and ideas in ways that will lead to more possibilities for future change and discovery. Dominant Ne prefers a new direction--any new direction--over repetition of anything that's been done before. Newness and novelty reign supreme as no stone goes unturned in the search for that which is different, special, or simply fascinating. Entrenched in a constant search for new varieties of experience and information, the ENFP is guided by equal parts curiosity about possibilities for change and desire to be perceived by others as on the cutting edge of pioneering creative spirit and unexpected new developments and connections. Fundamentally, Ne needs to feel appreciated by others for its unique approach, fascinating expertise, and inter-contextual understanding of the relationships between different ideas--if the audience hasn't considered those particular connections before, all the better for dominant Ne's image.

One thing many people often don't realize about ENFPs is that, despite the air of confident creativity they tend to project, dominant Ne often has no real idea of how valuable or meaningful its ideas are until they are validated by the feedback of other people the ENFP considers worthwhile or interesting. Because they operate primarily on a mindset that encourages exploring any and all possibilities just in case they happen to yield something interesting, they invariably come up with just as many (if not more) ideas that [I]don't[/I] lead anywhere as ideas that do. As a Pe function, dominant Ne picks a random starting point and then explodes into as many different directions as possible--ENFPs are often not nearly as interested in the evaluation or elimination of options as they are in the ever-expansive creation of more as-of-yet unconsidered options. The world is an open-ended set of patterns that begs to be experimented with and discovered--the more we search and expand, the more we will realize that whatever we think now is probably going to change into something else soon enough. Permanency is frequently an issue: even if we enjoy something today, we might very well discover something even better tomorrow. Dominant Ne sees no reason to stop searching and testing out every combination--after all, any kind of unexpected event may happen at any time, and that might very well lead into a completely different direction that we hadn't even considered yet. (And that might very well be [I]really[/I] interesting!)

Few types struggle more with the battle against boredom than ENFPs. As Pe dominants, they have high thresholds for external stimulation, and they may find themselves desperately in need of more experiences, more interests, more hobbies--anything that provides more options for different methods of exploration into new areas that might provide interesting connections to even newer areas we don't even know about yet. Dominant Ne tends to think in a sort of outwardly spiraling web of free association--casting a net out into the sea of all possibilities, no matter how seemingly trivial, and picking out broad, macro-level similarities between contexts never before considered similar. Indeed, ENFPs can pick out [I]some[/I] sort of similarity or conceptual connection between virtually anything, and can often be spotted via their continual insistence on pointing out and describing these free associations to others. Since it depends on objective, external information, dominant Ne [I]must[/I] have a core group of individuals against whom it can check the "interest level" and flow of its ideas. From an Ne standpoint, if I can't make others understand it, how can I expect to connect it to any other external application or development?

Often quite by accident, this tendency leads ENFPs to develop a fluency for "translation" of complex ideas into terms their audiences already understand. Because the Ne dominant learns new ideas through the same process--constructing conceptual metaphors that represent relationships between new ideas by observing similarities between them--he may find, much to his own surprise, that he's likely very good at finding similar conceptual relationships that will clarify ideas and concepts for others. His extroverted need to make others understand his ideas in order to understand them himself may become an unlikely strength: it facilitates a robust level of communication that grants ENFPs their reputation as teachers, innovators, and personal motivators. The natural ability to do so leads most ENFPs to develop their self-images around their creative, communicative, and interpersonal abilities--they need to be seen as forward-thinking and progressive, yet humanistic and empathetic. It's important that others perceive them as different and unique, yet similar enough to relate to.

[B]Auxiliary: Introverted Feeling (Fi)[/B]

[I]"I'm sick of painting in black and white / My pen is dry, now I'm uptight / So sick of limiting myself to fit your definition"[/I]
--Incubus, "Redefine" (lyrics by Brandon Boyd, ENFP)

Behind the public face lies the more introspective side of the ENFP's character represented by auxiliary Fi. The importance of Fi for ENFPs is no different from the role of Ji in the cognitive hierarchy of all four ExxP types: it provides a sense of individualized identity and an internal compass by which to weigh external expectations against one's own private values. Most ENFPs have a certain sense of the theatrical--many find work in performance roles where their ability to play to the expectations of an audience (a generally common Pe characteristic) leads to a natural flair for entertainment ability (in these situations it's often easy to confuse them with ESFPs), as well as a sense of connectedness to that which affects the human soul, the sense of compassion and identification to that which people will find [I]moving[/I]. While Fi tends to judge this sort of aesthetic on a purely personal basis, Ne connects the ENFP's own emotional and critical responses back to his awareness of the expectations of what his peer groups will perceive as attention-worthy and unique. In this way, Fi helps to balance artistic integrity and personal identity against the aesthetic expectations of the audience in question.

This may present both a gift and something of a difficult conundrum for the young ENFP: naturally more in tune with the perceptions and expectations of her friends and peer groups than with her own private identity, the ENFP seeking to appease auxiliary Fi may feel highly conflicted when her desire to lead the charge into the unknown contradicts her personal feeling that something isn't right, that someone is being treated unfairly, that something isn't being approached with complete integrity. In the process of developing Fi, it's not uncommon to see ENFPs loudly and bluntly declaring their moral opposition to situations they find unconscionable: as Fi builds an increasingly steady position in their cognitive hierarchies, ENFPs are forced to confront the fact that sometimes, standing up for what's right means subjecting themselves to the hatred and indiscretion of the people they'd normally want to impress and identify with.

Potentially even more importantly, Fi creates a connection to the ethical principles and static internal "universal truths" that guide the ENFP to a sense of confidence that what he's doing is consistent with the way he feels is his duty to contribute to a global sense of the greater good. It lends shape and direction to Ne's unchained creative explosions, allowing its need for constant change and redefinition to incorporate Worthy Causes and Good Deeds into its goals and ambitions. With a strong Ne/Fi balance in effect, the well-rounded ENFP will develop his peer groups around his sense of moral integrity: Fi is sure to surround itself with people who will reinforce the positive aspects of Ne's externally reflective properties. By choosing friends and associates that Fi deems worthwhile and respectable people, the ENFP can fulfill Ne's desire to appear progressive and original while ensuring that the people to whom he caters his appearance are individuals of integrity--ENFPs invariably hold high opinions of the people they call true friends.

To be fair, Fi is also responsible for the stereotype that ENFPs are, occasionally, a bit easily hurt. While this accusation is probably more applicable to Fi dominant types than Fi auxiliary, there's a crucial difference between Fi as a dominant function and Fi as an auxiliary: ENFPs are much less guarded with personal feelings and information than are their INFP counterparts. They tend to feel that most information should be given up front, so that all parties can be sure they know what they're getting into. But not only do they share information more readily than INFPs, they also depend more directly on the response or validation of people they've chosen as worthwhile role models or important equals. Fundamentally, ENFPs need to get others excited about their ideas, and they need to have the freedom to spread out and explore those ideas as much as possible. If they feel their contributions are being ignored or that they aren't being respected, they may temporarily forget their characteristic friendly demeanor. They invariably feel threatened by any attempt to restrict their freedom or unduly influence their moral character--they are characteristically distrustful of externalized directions ("the man" is not, under any circumstances, to be trusted) on how they should think, feel, or live their lives.

[B]Tertiary: Extroverted Thinking (Te)[/B]

As time passes and maturity develops, the ENFP must come to terms with his need for constant freedom to change external conditions at any given time. Often, tertiary Te is responsible for helping the ENFP develop a sense of structure and organized progression to his life. As he thrives on exploring new contexts, the ENFP with poor Te may feel fulfilled while he is directly engaged in pursuits he enjoys, but he may also have difficulty building any high level of skill in any one particular area, and will likely lack the planning and organizational ability to develop his passions into productive or profitable pursuits. Because starting a new project is often so much more exciting (after all, it holds the optimistic hope of unknown possibilities, where Ne feels most at home) than following through and completing projects already begun, poor Te development may result in some rather blatant procrastination issues. While healthy ExxP types tend to maintain fairly high energy levels, poorly developed or depressed ExxPs will have extreme difficulty even starting on unpleasant or uninteresting tasks. Te development is responsible for a shift in perspective toward the value in objective measurement and evaluation, out of the scope of the personalized value judgments in which Fi specializes.

While young ENFPs may often lack direction or consistent attention to detail earlier in life, the introduction of tertiary Te begins to produce the realization that, simply put, not everything can be turned into play time--and although we should choose our careers around that which we find fulfilling, we also must learn to put up with some uninteresting activities and press forward in the name of realistic results. When applied tastefully and in balance with Ne and Fi, tertiary Te will grant the ENFP some unexpected leadership abilities: willing to experiment with different ideas, but with an eye on the creation and scheduled completion of realistic steps. Te should, ideally, assist Ne in the realization of its visions for the future: by thinking concretely about the necessary procedures and the (sometimes externally imposed!) judgments of those in positions of authority, the ENFP will find he can, occasionally, set aside his personal feelings aside in favor of getting more important matters under control. Bearing a realistic agenda with measurable checkpoints for tangible progress, Te creates a (sometimes sorely missed) sense of the realities of how business is handled in a self-interested world.

If Fi is, for some reason, poorly developed, NeTe may create an unpredictable and volatile personality torn between desire for admiration of his creative expressions and a need to uphold and enforce objective order on the world around him. One of the best examples of "NeTe loop" that I can think of is Steve Carrell's character on the American version of [I]The Office[/I]--deathly desirous of the approval and adulation of his employees (Ne), he snaps abruptly into Te mode and begins barking orders and criticisms whenever his attempts to reach out for personal connections (Fi) are rejected. As a defense mechanism against feelings of being personally attacked, Te takes the opportunity to remind everyone of his objectively enforceable authority ("The Boss") in order to make others feel as belittled as he does by what he sees as their deliberate and inhumane rejection of the value of his personal identity. Later, Ne reminds him that he's not going to get anyone to like him with that sort of behavior, and Fi feels bad for upsetting people--it knows all too well what that feels like--but he's not getting the kind of validation that an ENFP thrives on, so his Fi is forced to hide behind an angry, exaggerated Te mask.

[B]Inferior: Introverted Sensation (Si)[/B]

Most commonly, inferior Si seems responsible for throwing a wrench in dominant Ne's constant insistence on exploring the unknown. Si represents the comfort of the known, the total certainty of consistent interpretation of the sensory data associated with a familiar experience. Ironically, inferior Si actually embeds itself subconsciously in the way ENFPs develop a certain familiarity with finding comfort in the unfamiliar: when all parties begin with no information, inferior Si may actually promote a certain comfortable familiarity with "starting from scratch." Being forced to compete in a new, difficult area where substantial real experience is required may throw the ENFP out of her comfort zone as she is forced to intuit how to handle a new situation, but stay ahead of someone who already knows all the answers. As Pe dominant types, ENFPs may find themselves so good at "winging it" through everything with little to no preparation that they allow their improvisational talents to replace the development of legitimate work and study skills. This works up to a point, but eventually the ENFP will encounter challenges he cannot surpass purely with quick wit and Ne-ducated guessing.

Inferior Si also seems, in the ENFP's more stressful moments, to reinforce mounting fears of a static, always predictable world where we are locked into one course of action and no room for innovation or personal expression remains. This scenario is the ENFP's worst nightmare: forever locked into the same boring, repetitive, mind-numbing repetition of the same predictable and uninteresting events. In the grip of an Si attack, the ENFP may fear that none of his visions have any real value if they are not felt in a tangible and permanent manner, that wandering into new territory will always feel just like the territory we already know, and that we will never be able to fulfill our subconscious need for the consistent feeling (Si) of constant change and adaptation (Ne) because "nothing will ever really change." Mired in this feeling of failure to effect any sort of external change (something Ne tends to find intolerable), ENFPs in the grip of Si may lose their characteristic excited energy and resign themselves to harsh criticism and self-doubt. (In rare cases, this may even combine with Te to deliberately attack or demean others as a means of reestablishing the ENFP's own feeling of self-worth.)

The ultimate purpose of Si for an Ne dominant should be to provide a concrete balance in the real world, to weigh against Ne's constant discontent with the tangible realities of the present moment. Much like ENTPs, ENFPs at their worst will indulge in comfortable familiar experiences, but while these experiences usually center around rebuilding a feeling of technical competence for ENTPs, for ENFPs it's most often directed at rehabilitating the unique value of one's personal identity and sense of self-expression. They may retreat home and indulge in the consistently positive feedback of close friends and family that they know will encourage them when they need it. When the chips are down, creating a little familiarity, leaving a rope by which to climb back to where we started, begins to strike the ENFP as an increasingly prudent idea the more he grows and TeSi embeds itself further into his perspective.

When applied in balance with the other functions, Si should provide the ENFP with a sense of peace in the ability to be happy with what he has, to appreciate the value in that which is already established, to absorb the best things about that which already is, and to remember their value when the inevitable necessity of change eventually arises. Balanced Si provides Ne dominants with a realistic grounding in something worth holding onto for the sake of helping define our identities by the experiences we've had and the impressions we've created of them. As she begins to coalesce her divergent interests into specific areas with real, concrete applications, Si will provide the ENFP a safe place to return to in the event that exploratory efforts prove unsuccessful. The occasional pause for reflection on lessons past will serve as an anchor that holds the solemn duty of preventing Icarus from flying too close to the sun--a lesson every ENFP can likely find value in.
```

**Comment by akhoury** [comment] 2015-01-08 03:45
I think there is a different issue, I cannot reproduce the issue using the [bbcode-to-markdown](https://github.com/akhoury/bbcode-to-markdown), check this [test case](https://gist.github.com/akhoury/0e4c7c58268685c41ce5)

Can you screenshot the part where you've setup the config?
Go to the Import in the Admin Panel > Post Import Tools > Content Conversion 

kind of like this one
https://camo.githubusercontent.com/0a31a0c76572dfa09c03b4319245bb940986f229/687474703a2f2f692e696d6775722e636f6d2f6161574c4f52692e706e67

Stupid question, you did click "Start Convert" and waited right?

**Comment by nhlpl** [comment] 2015-02-25 08:47
vBulletin 3.8.x > NodeBB 0.6.1 works as it should. You need to activate Markdown plugin to see changes.

**Comment by akhoury** [comment] 2015-02-25 14:45
^ correct !

**Comment by akhoury** [comment] 2015-03-04 02:52
closing as not a bug

**Closed by akhoury** 2015-03-04 02:52 UTC
