### ISSUE TITLE
Post-import type-error

### ISSUE THREAD

**Issue by hehol** [akhoury/nodebb-plugin-import#184] opened 2016-03-29 07:51 UTC
I'm using the Git commit c4c2bd1fbb9963d5479359a56191ccf51d42e8cb of nodebb-plugin-import and commit bb1ee62cc846d33a09146e6c1e8d6ddba5a8e72b of nodebb-plugin-import-vbulletin. During post-import conversion, I get this error:

```
29/3 09:38 [22407] - error: TypeError: Cannot read property 'implementation' of undefined
    at Function.getListeners (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:176:74)
    at Function.dispatch (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:192:40)
    at Object.events.EventTarget.dispatchEvent (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:287:33)
    at Object.DOMWindow.dispatchEvent (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/jsdom-nogyp/lib/jsdom/browser/index.js:114:40)
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/jsdom-nogyp/lib/jsdom/browser/index.js:50:16
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
TypeError: Cannot read property 'implementation' of undefined
    at Function.getListeners (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:176:74)
    at Function.dispatch (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:192:40)
    at Object.events.EventTarget.dispatchEvent (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:287:33)
    at Object.DOMWindow.dispatchEvent (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/jsdom-nogyp/lib/jsdom/browser/index.js:114:40)
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/node_modules/jsdom-nogyp/lib/jsdom/browser/index.js:50:16
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
```

Did this error cause the entire post-import process to abort or was it just a problem converting a single item in the database?

**Comment by akhoury** [comment] 2016-04-01 00:11
yes it did stop the post-import process, this bug is a duplicate of 
https://github.com/akhoury/nodebb-plugin-import/issues/179

will fix this weekend, closing as duplicate

**Closed by akhoury** 2016-04-01 00:11 UTC
